dist: focal
os: linux

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pip install -U pip
  - pip install awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER

install: skip

jobs:
  include:
    - stage: "BUILD"
      language: java
      jdk: oraclejdk11
      script:
        - ./gradlew build
        - cp build/libs/mundiagua_kotlin-serverless-all.jar ~/$TRAVIS_BUILD_NUMBER/.
        - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://$S3_BUILD_BUCKET/$TRAVIS_BUILD_NUMBER

    - stage: "DEPLOY DEVELOPMENT"
      if: branch != master
      language: node_js
      node_js:
        - node
      cache:
        directories:
          - node_modules
      script:
        - aws s3 sync s3://$S3_BUILD_BUCKET/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
        - npm install -g serverless
        - sls deploy --artifact=$(realpath ~/$TRAVIS_BUILD_NUMBER/mundiagua_kotlin-serverless-all.jar) --stage=dev --userpool=$AWS_USER_POOL_DEV

    - stage: "DEPLOY PRODUCTION"
      if: branch = master
      language: node_js
      node_js:
        - node
      cache:
        directories:
          - node_modules
      script:
        - aws s3 sync s3://$S3_BUILD_BUCKET/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
        - npm install -g serverless
        - sls deploy --artifact=$(realpath ~/$TRAVIS_BUILD_NUMBER/mundiagua_kotlin-serverless-all.jar) --stage=prod --userpool=$AWS_USER_POOL_PROD

    - stage: "CLEAN S3"
      script:
        - aws s3 rm s3://$S3_BUILD_BUCKET/$TRAVIS_BUILD_NUMBER --recursive